services:
  backend:
    build:
      context: .
      dockerfile: DockerFile.backend
    container_name: rag-backend
    ports:
      - "1005:8000"
    env_file:
      - .env
    volumes:
      - vectorstore_data:/app/vectorstore
    restart: unless-stopped



volumes:
  vectorstore_data:
    driver: local